name: Deploy - Azure Web App

on:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME: App-DevOpsChallenge-Action  
  AZURE_WEBAPP_PACKAGE_PATH: '.'      
  NUGET_VERSION: '5.3.1'           

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      
    - name: Run MSBuild
      run: msbuild .\Nibo.DevOpsChallenge.sln
       
    - name: Azure webapp deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Nibo.DevOpsChallenge/'
  
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
